---
title: "ANALISIS ESTADISTICO"
author: "Armando Arredondo Valle"
date: "23/5/2022"
toc: True
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducción:
<div>
  <style>
    p{
      text-align:justify;
    }
  </style>  
  <p>
  En este proyecto, buscamos realizar el análisis de los datos para una empresa la cual presenta un problema de materiales, en la cual existe una tendencia en la falla de materiales con base a que el personal capacitado..

  </p>  
</div>

<h3> Librerias a utilizar </h3> 
```{r eval=FALSE}

library("skimr")
library("naniar")
library("Hmisc")
library("corrplot")
library("psych")
library("dplyr")
library("GGally")
library("kableExtra")
```

```{r include=FALSE}

library("skimr")
library("naniar")
library("Hmisc")
library("corrplot")
library("psych")
library("dplyr")
library("GGally")
library("kableExtra")

```
<h2> Tablas de análisis </h2>

<h3> Tabla 1: <h3>

```{r echo=FALSE}
analyze = readxl::read_excel(sheet=1, path = "./datos.xlsx");
limpios = analyze %>% select(-Mes,-"Piezas producidas A",-"Piezas Producidas B",-"Piezas Producidas C")
colnames(limpios) <- c("DEFECTUOSAS A","DEFECTUOSAS B","DEFECTUOSAS C");
limpios
```

<h3> Tabla 2: <h3>
```{r echo=FALSE}


analyze2 = readxl::read_excel(sheet=3, path = "./ORIGINAL.xlsx",skip=1);

colnames(analyze2) <- c("Pressure", "PlasticPumpTemperature", "PlasticMixerTemperature", "ScrewTemperature", "ScrewRPM", "BarrelTemperature", "ExtrusionVelocity", "CoolerTemperature", "RawMaterialType", "ErrorPercentage");
analyze2 %>%
  kbl() %>%
  kable_styling()

```




